name: Build and Release

on:
  push:
    branches:
      - main  # 设置触发分支
	 
env:
  KERNEL_VERSION: 5.14.0
  BUSYBOX_VERSION: 1.34.0
  ARCH: x86_64
  ROOTFS_DIR: rootfs
  FS_IMG: rootfs.cpio.gz
  IMG_FILE: myimage.img
  IMG_SIZE: 100M
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update -y
        sudo -E apt-get -qq install -y gawk git gettext libssl-dev xsltproc zip git-core wget curl grep python2.7 python3 python3-pip libpython3-dev
        sudo timedatectl set-timezone "${{ env.TZ }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: 编译内核
      run: |
        wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL_VERSION}.tar.xz
        tar -xvf linux-${KERNEL_VERSION}.tar.xz
        cd linux-${KERNEL_VERSION}
        make ARCH=${ARCH} defconfig
        make ARCH=${ARCH} -j$(nproc)

    - name: 编译busybox
      run: |
        wget https://busybox.net/downloads/busybox-${BUSYBOX_VERSION}.tar.bz2
        tar -xvf busybox-${BUSYBOX_VERSION}.tar.bz2
        cd busybox-${BUSYBOX_VERSION}
        make defconfig
        make -j$(nproc)

    - name: 创建文件系统镜像
      run: |
        mkdir -p $(ROOTFS_DIR)/bin
        cp busybox-$(BUSYBOX_VERSION)/busybox $(ROOTFS_DIR)/bin/
        cd $(ROOTFS_DIR) && \
        ln -s bin/init init
        echo "#!/bin/sh" > $(ROOTFS_DIR)/init
        echo "mount -t proc none /proc" >> $(ROOTFS_DIR)/init
        echo "mount -t sysfs none /sys" >> $(ROOTFS_DIR)/init
        echo "exec /bin/sh" >> $(ROOTFS_DIR)/init
        chmod +x $(ROOTFS_DIR)/init
        cd $(ROOTFS_DIR) && \
        find . | cpio -o --format=newc > ../$(FS_IMG)
        cd .. && \
        gzip -c $(FS_IMG) > $(FS_IMG)

    - name: 生成镜像文件
      run: |
        dd if=/dev/zero of=$(IMG_FILE) bs=1 count=0 seek=$(IMG_SIZE)
        parted $(IMG_FILE) mklabel msdos
        parted $(IMG_FILE) mkpart primary ext4 1 100%
        mkfs.ext4 -F $(IMG_FILE)
        mkdir -p /mnt/loop
        sudo mount -o loop $(IMG_FILE) /mnt/loop
        sudo cp $(FS_IMG) /mnt/loop
        sudo umount /mnt/loop

    - name: 发布到 Release
      id: publish-release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          myimage.img
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          这是磁盘镜像的发布。
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
