name: Build and Release

on:
  push:
    branches:
      - main  # 设置触发分支
	 
env:
	KERNEL_VERSION : ${{5.14.0}}
	BUSYBOX_VERSION : ${{1.34.0}}
	ARCH : ${{x86_64}}
	ROOTFS_DIR : ${{rootfs}}
	FS_IMG : ${{rootfs.cpio.gz}}
	IMG_FILE : {{myimage.img}}
	IMG_SIZE : {{100M}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 编译内核
      run: |
		wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-$(KERNEL_VERSION).tar.xz
		tar -xvf linux-$(KERNEL_VERSION).tar.xz
		cd linux-$(KERNEL_VERSION) 
		make ARCH=$(ARCH) defconfig 
		make ARCH=$(ARCH) -j$(nproc)
		

    - name: 编译busybox
      run: |
		wget https://busybox.net/downloads/busybox-$(BUSYBOX_VERSION).tar.bz2
		tar -xvf busybox-$(BUSYBOX_VERSION).tar.bz2
		cd busybox-$(BUSYBOX_VERSION) 
		make defconfig 
		make -j$(nproc)
		
    - name: 编译busybox
      run: |
		mkdir -p $(ROOTFS_DIR)/bin
		cp busybox-$(BUSYBOX_VERSION)/busybox $(ROOTFS_DIR)/bin/
		cd $(ROOTFS_DIR) && \
		ln -s bin/init init
		echo "#!/bin/sh" > $(ROOTFS_DIR)/init
		echo "mount -t proc none /proc" >> $(ROOTFS_DIR)/init
		echo "mount -t sysfs none /sys" >> $(ROOTFS_DIR)/init
		echo "exec /bin/sh" >> $(ROOTFS_DIR)/init
		chmod +x $(ROOTFS_DIR)/init
		cd $(ROOTFS_DIR) && \
		find . | cpio -o --format=newc > ../$(FS_IMG)
		cd .. && \
		gzip -c $(FS_IMG) > $(FS_IMG)
		
		
		
    - name: 创建文件系统镜像
      run: |
		dd if=/dev/zero of=$(IMG_FILE) bs=1 count=0 seek=$(IMG_SIZE)
		parted $(IMG_FILE) mklabel msdos
		parted $(IMG_FILE) mkpart primary ext4 1 100%
		mkfs.ext4 -F $(IMG_FILE)
		mkdir -p /mnt/loop
		sudo mount -o loop $(IMG_FILE) /mnt/loop
		sudo cp $(FS_IMG) /mnt/loop
		sudo umount /mnt/loop

	  

    - name: Publish to Release
      id: publish-release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          myimage.img
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          This is the release of the disk image.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
