name: Build and Release


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 编译内核
      run: |
		wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.14.0.tar.xz
		tar -xvf linux-5.14.0.tar.xz
		cd linux-5.14.0 
		make ARCH=1.34.0 defconfig 
		make ARCH=x86_64 -j$(nproc)
		

    - name: 编译busybox
      run: |
		wget https://busybox.net/downloads/busybox-1.34.0.tar.bz2
		tar -xvf busybox-1.34.0.tar.bz2
		cd busybox-1.34.0 
		make defconfig 
		make -j$(nproc)
		
    - name: 编译busybox
      run: |
		mkdir -p rootfs/bin
		cp busybox-1.34.0/busybox rootfs/bin/
		cd rootfs && \
		ln -s bin/init init
		echo "#!/bin/sh" > rootfs/init
		echo "mount -t proc none /proc" >> rootfs/init
		echo "mount -t sysfs none /sys" >> rootfs/init
		echo "exec /bin/sh" >> rootfs/init
		chmod +x rootfs/init
		cd rootfs && \
		find . | cpio -o --format=newc > ../rootfs.cpio.gz
		cd .. && \
		gzip -c rootfs.cpio.gz > rootfs.cpio.gz
		
		
		
    - name: 创建文件系统镜像
      run: |
		dd if=/dev/zero of=myimage.img bs=1 count=0 seek=100M
		parted myimage.img mklabel msdos
		parted myimage.img mkpart primary ext4 1 100%
		mkfs.ext4 -F myimage.img
		mkdir -p /mnt/loop
		sudo mount -o loop myimage.img /mnt/loop
		sudo cp rootfs.cpio.gz /mnt/loop
		sudo umount /mnt/loop

	  

    - name: Publish to Release
      id: publish-release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          myimage.img
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          This is the release of the disk image.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
